Feature/day time
EgoreTTa/MiniGame pull request #10
Opened 2023-08-02 17:55 UTC by Marina-rina

2023-08-02 18:00 UTC, EgoreTTa requested changes

2023-08-02 18:00 UTC, EgoreTTa commented on Assets/DayTime.cs
> +// Update is called once per frame
убрать

2023-08-02 18:00 UTC, EgoreTTa commented on Assets/DayTime.cs
> +    public DayParts PartOfDay
public DayParts PartOfDay => _dayTime;

2023-08-02 18:00 UTC, EgoreTTa commented on Assets/DayTime.cs
> +    void Update()
private void Update()

2023-08-02 18:00 UTC, EgoreTTa commented on Assets/DayTime.cs
> +        switch ((int)_time / 21600)
вынести константу _partOfDayForSecond = 21600

2023-08-02 18:00 UTC, EgoreTTa commented on Assets/DayTime.cs
> +                _time -= 86400;
вынести константу _secondOfDay = 86400

2023-08-02 18:00 UTC, EgoreTTa commented on Assets/DayTime.cs
> +        Debug.Log(_dayTime);
Debug не нужен в готовой версии

2023-08-04 17:01 UTC, Marina-rina commented on Assets/DayTime.cs
> +// Update is called once per frame
убрано

2023-08-04 17:08 UTC, EgoreTTa approved these changes

2023-08-04 20:51 UTC, DarkTinker23 approved these changes
Согласовано, вопросов нет

2023-08-05 05:37 UTC, merged