Clone PR #18
EgoreTTa/MiniGame pull request #2
Opened 2023-07-28 14:37 UTC by EgoreTTa

2023-07-28 17:33 UTC, Marina-rina requested changes

2023-07-28 17:33 UTC, Marina-rina commented on Assets/BaseEffect.cs
> +    public virtual void PreStartEffect(BaseMob target) { }
delete

2023-07-29 08:52 UTC, DarkTinker23 requested changes
Перепроверь

2023-07-30 04:02 UTC, DarkTinker23 approved these changes
Можно оставить название эффекта , просто в дальнейшем изменим эффект

2023-07-30 04:02 UTC, DarkTinker23 commented on Assets/HangoverEffect.cs
> +using UnityEngine;
Есть возможность переименовать класс (мы же отходим от тематики бомжей)? Чтобы в дальнейшем путаницы не было ?

2023-07-31 11:22 UTC, EgoreTTa commented on Assets/HangoverEffect.cs
> +using UnityEngine;
Предлагай какое название класса хочешь. Эффект "Похмелье" отсюда и название класса

2023-07-31 11:23 UTC, EgoreTTa commented on Assets/HangoverEffect.cs
> +using UnityEngine;
Или Issue создай

2023-08-04 20:52 UTC, DarkTinker23 approved these changes
Ок

2023-08-04 20:52 UTC, DarkTinker23 approved these changes
Ок

2023-08-06 14:13 UTC, DarkTinker23 submitted a review, later dismissed

2023-08-06 14:21 UTC, DarkTinker23 approved these changes

2023-08-06 14:24 UTC, DarkTinker23 approved these changes

2023-08-06 14:24 UTC, DarkTinker23 approved these changes, later dismissed

2023-08-06 14:26 UTC, Marina-rina submitted a review, later dismissed

2023-08-06 14:26 UTC, Marina-rina approved these changes

2023-08-06 14:27 UTC, DarkTinker23 approved these changes

2023-08-06 14:27 UTC, merged

2023-08-06 14:27 UTC, DarkTinker23 approved these changes