Add Fire Set
EgoreTTa/MiniGame pull request #52
Opened 2023-08-28 21:36 UTC by DarkTinker23

Добавление огненного сэта

2023-08-28 21:45 UTC, EgoreTTa requested changes

2023-08-28 21:45 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireHelmet.cs
> +
форматирование
Убирать пустые строки

2023-08-28 21:45 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireHelmet.cs
> +        //      [SerializeField] private int Armor - ���� ��� ��������
Комменты не нужны

2023-08-28 21:45 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireHelmet.cs
> +
Пустые строчки

2023-08-28 21:45 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireHelmet.cs
> +
Пустые строчки

2023-08-28 21:45 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireHelmet.cs
> +        [SerializeField] private GameObject FireCircke;
```suggestion
        [SerializeField] private GameObject _fireCircke;
```

2023-08-28 21:45 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireHelmet.cs
> +            yield return new WaitForSeconds(1);
Я бы предложил сделать через invokerepeating

2023-08-30 05:45 UTC, EgoreTTa requested changes

2023-08-30 05:45 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireHelmet.cs
> +        private bool EquipBool = false;
Поле 
```suggestion
        private bool _equipBool = false;
```

2023-08-30 05:45 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireArmor.cs
> +        [SerializeField] private GameObject FireCircke;
```suggestion
        [SerializeField] private GameObject _fireCircke;
```
Поля именуются с префиксом _pascalCase

2023-08-30 05:45 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireArmor.cs
> +            InvokeRepeating("Regen", 0f, 1f);
Используй nameof

2023-08-30 05:45 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireBoot.cs
> +        [SerializeField] private GameObject FireCircke;
-||-

2023-08-30 05:45 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireBoot.cs
> +        private void Regen()
Не слепляй свойства и методы, один перенос

2023-08-30 05:45 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireBoot.cs
> +
Убрать

2023-08-30 05:45 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireBoot.cs
> +        public void Unequip()
Добавить переносы между методами

2023-08-30 05:45 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireBoot.cs
> +            InvokeRepeating("Regen", 0f, 1f);
-||-

2023-08-30 17:51 UTC, EgoreTTa requested changes

2023-08-30 17:51 UTC, EgoreTTa commented on Assets/Scripts/Items/Vodka.cs
> +
```suggestion

```

2023-08-30 17:51 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireHelmet.cs
> +
```suggestion
```

2023-08-30 17:51 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireHelmet.cs
> +        }
```suggestion
        }

```

2023-08-30 17:51 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireHelmet.cs
> +            InvokeRepeating("Regen", 0f, 1f);
```suggestion
            InvokeRepeating(nameof(Regen), 0f, 1f);
```

2023-08-30 17:51 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireHelmet.cs
> +        public TypesEquipment TypeEquipment => _typeEquipment;
```suggestion
        public TypesEquipment TypeEquipment => _typeEquipment;

```

2023-08-30 17:51 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireHelmet.cs
> +        [SerializeField] private TypesEquipment _typeEquipment;
```suggestion
        [SerializeField] private TypesEquipment _typeEquipment;

```

2023-08-30 17:51 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireBoot.cs
> +
```suggestion
```

2023-08-30 17:51 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireBoot.cs
> +
```suggestion
```

2023-08-30 17:51 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireArmor.cs
> +
```suggestion
```

2023-09-03 08:01 UTC, EgoreTTa requested changes

2023-09-03 08:01 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireArmor.cs
> +        public TypesEquipment TypeEquipment => _typeEquipment;
Отделить свойство от полей

2023-09-03 08:01 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireBoot.cs
> +        public TypesEquipment TypeEquipment => _typeEquipment;
Отделить свойство от полей

2023-09-03 10:14 UTC, Marina-rina requested changes

2023-09-03 10:14 UTC, Marina-rina commented on Assets/Scripts/Items/Equipments/FireArmor.cs
> +        [SerializeField] private GameObject _fireCircke;
Неиспользуемое поле. Убрать

2023-09-03 10:14 UTC, Marina-rina commented on Assets/Scripts/Items/Equipments/FireBoot.cs
> +        [SerializeField] private GameObject _fireCircke;
Неиспользуемое поле. Убрать

2023-09-03 10:14 UTC, Marina-rina commented on Assets/Scripts/Items/Equipments/FireHelmet.cs
> +        [SerializeField] private GameObject _fireCircke;
Неиспользуемое поле. Убрать

2023-09-12 14:49 UTC, EgoreTTa requested changes

2023-09-12 14:49 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireBoot.cs
> +        [SerializeField] private float _changeRegeneration;
```suggestion
        [SerializeField] private float _intervalRegeneration;
```

2023-09-24 13:08 UTC, EgoreTTa approved these changes

2023-09-24 13:11 UTC, Marina-rina approved these changes

2023-09-24 13:11 UTC, merged