Добавление эффекта при сборке огненного сэта
EgoreTTa/MiniGame pull request #60
Opened 2023-10-01 18:18 UTC by DarkTinker23

2023-10-02 04:39 UTC, EgoreTTa requested changes

2023-10-02 04:39 UTC, EgoreTTa commented on Assets/Scripts/Abilities/BaseSkill.cs
> +        }
К скилу никак не относится.
Используй интерфейс IAbility

2023-10-02 04:39 UTC, EgoreTTa commented on Assets/Scripts/Abilities/FireCirle.cs
> +                _healthSystems[i]?.TakeDamage(_damage);
Систему здоровья на null проверяешь?
Проверяй жив ли объект, свойство Life

2023-10-02 04:39 UTC, EgoreTTa commented on Assets/Scripts/Abilities/FireCirle.cs
> +        void Awake()
```suggestion
        private void Awake()
```

2023-10-02 04:39 UTC, EgoreTTa commented on Assets/Scripts/Abilities/FireCirle.cs
> +        void Update()
```suggestion
        private void Update()
```

2023-10-02 04:39 UTC, EgoreTTa commented on Assets/Scripts/Abilities/FireCirle.cs
> +            set => _active = value;
Скорее всего нужно вынести set в отдельный метод.

2023-10-02 04:39 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireArmor.cs
> +            if (_owner.Inventory.Helmet?.NameItem == ElememtSetHelmet.NameItem &&
Сделать проверку через enum

2023-10-02 04:39 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireArmor.cs
> +                    Debug.Log("�� ���� �����");
Убрать Debug

2023-10-02 04:39 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireArmor.cs
> +                FireCirlceSpell = CheckSkill();
Переименовать метод.

2023-10-02 04:39 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireBoot.cs
> +    using Skills;
У нас есть Abilities, разве это нужно?

2023-10-03 15:55 UTC, Marina-rina requested changes

2023-10-03 15:55 UTC, Marina-rina commented on Assets/Scripts/Abilities/FireCirle.cs
> +    public class FireCirle : BaseSkill
Переименовать из FireCirle в FireCircle

2023-10-03 15:55 UTC, Marina-rina commented on Assets/Prefabs/Equipments/FireCirlceSpell.prefab
Переименовать из FireCirlceSpell в FireCircleSpell

2023-10-03 15:55 UTC, Marina-rina commented on Assets/Scripts/Items/Equipments/FireArmor.cs
> +            if (_owner.GetComponentsInChildren<FireCirle>() is { } fireCirles)
Переименовать из fireCirles в fireCircles

2023-10-03 15:55 UTC, Marina-rina commented on Assets/Scripts/Items/Equipments/FireHelmet.cs
> +        [SerializeField] private BaseItem ElememtSetArmor;
Переименовать из ElememtSetArmor в ElementSetArmor

2023-10-03 15:55 UTC, Marina-rina commented on Assets/Scripts/Items/Equipments/FireHelmet.cs
> +        [SerializeField] private BaseItem ElememtSetBoot;
Переименовать из ElememtSetBoot в ElementSetBoot

2023-10-03 16:24 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireHelmet.cs
> +        [SerializeField] private BaseItem ElememtSetBoot;
```suggestion
        [SerializeField] private BaseItem _elememtSetBoot;;
```

2023-10-03 16:24 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireHelmet.cs
> +        [SerializeField] private BaseItem ElememtSetArmor;
```suggestion
        [SerializeField] private BaseItem _elementSetArmor;
```

2023-10-05 15:37 UTC, DarkTinker23 commented on Assets/Prefabs/Equipments/FireCirlceSpell.prefab
Переменная не найдена

2023-10-05 15:37 UTC, DarkTinker23 commented on Assets/Scripts/Items/Equipments/FireArmor.cs
> +            if (_owner.GetComponentsInChildren<FireCirle>() is { } fireCirles)
Переменной более не существует

2023-10-05 15:56 UTC, EgoreTTa requested changes

2023-10-05 15:56 UTC, EgoreTTa commented on Assets/Scripts/Abilities/FireCirсle.cs
> +            if (_healthSystems is not null)
Он никогда не будет null, ты его проинициализировал. Он может быть пустым, поправь

2023-10-05 15:56 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireArmor.cs
> +        private FireCircle FindSkill;
Наименование класса
Наименование поле _pascalCase

2023-10-05 15:56 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireBoot.cs
> +        private FireCircle FindSkill;
-||-

2023-10-05 15:56 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireHelmet.cs
> +        private FireCircle FindSkill;
-||-

2023-10-05 16:09 UTC, EgoreTTa requested changes

2023-10-05 16:09 UTC, EgoreTTa commented on Assets/Scripts/Abilities/FireCirсle.cs
> +                    collider.GetComponent<BaseMob>().IsLive == true)
```suggestion
                    collider.GetComponent<BaseMob>().IsLive is true)
```

2023-10-05 16:38 UTC, EgoreTTa requested changes

2023-10-05 16:38 UTC, EgoreTTa commented on Assets/Scripts/Abilities/BaseSkill.cs
> +    public abstract class BaseSkill : MonoBehaviour
удалить

2023-10-05 16:38 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireArmor.cs
> +        private FireCircle FindSkill;
удалить

2023-10-05 16:38 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireArmor.cs
> +            FindSkill = HelpLibraryForEquipmentSet.CheckSkill(_owner) as FireCircle;
```suggestion
            var effect = HelpLibraryForEquipmentSet.CheckEffect(_owner) as FireCircle;
```

2023-10-05 16:38 UTC, EgoreTTa commented on Assets/Scripts/Items/Equipments/FireArmor.cs
> +            if (FindSkill != null)
```suggestion
            if (effect!= null)
```

2023-10-05 17:13 UTC, EgoreTTa submitted a review, later dismissed

2023-10-05 22:15 UTC, EgoreTTa approved these changes

2023-10-05 22:15 UTC, EgoreTTa commented on Assets/Scripts/Effects/FireCirсle.cs
> +
лишняя строка

2023-10-08 15:43 UTC, Marina-rina approved these changes

2023-10-08 16:28 UTC, merged